### ISSUE TITLE
请问如何将第三方功能加到react native中？

### ISSUE THREAD

**Issue by ShotGunYuan** [weflex/react-native-wechat#1]
比如：alipay  微信支付  百度地图

**Comment by yorkie** [comment]
你需要阅读这里：http://facebook.github.io/react-native/docs/native-modules-ios.html#content

**Comment by ShotGunYuan** [comment]
十分感谢！

**Comment by yorkie** [comment]
不客气哟，请继续关注我们WeFlex，之后还会继续开源出大量的类似Binding出来 :-)
