### ISSUE TITLE
android: 导入 import com.theweflex.react.WeChatPackage; 出错

### ISSUE THREAD

**Issue by jlala** [weflex/react-native-wechat#101]
![image](https://cloud.githubusercontent.com/assets/8163601/17849690/8e356946-688c-11e6-8276-13dfcba0e32c.png)

现在android工程下，， 有 两个这样的文件，mainapplication里面加入了 wechatpackage() 但是运行报错了

**Comment by yorkie** [comment]
是 gradle 项目？

**Comment by jlala** [comment]
就是 新建 react-native 工程，下面的androud 现在main文件有两个 ，您可以简单生成一个rn项目看下呢

**Comment by yorkie** [comment]
@jlala 还是没有明白是什么问题，你在 mainapplication.java 中 import 之后报错信息是什么？

**Comment by jlala** [comment]
![image](https://cloud.githubusercontent.com/assets/8163601/17891225/000376e0-696d-11e6-8b10-2de85856fea1.png)
我加群了 通过一下

**Comment by jlala** [comment]
@yorkie 您好 我修改好了， 是我这边的问题，rnpm link之后 其实有些地方是不需要改的 我有按教程重复加上了 : RCTWeChat这个 导致错误了，搞得太晚没看清郁闷呀 可以关掉了呢

**Comment by yorkie** [comment]
哦哦，好的，入群申请也通过了 :)
