### ISSUE TITLE
sendAuthRequest 没有收到response

### ISSUE THREAD

**Issue by litstrong** [weflex/react-native-wechat#102]
按照要求配置了，检查了wechat的api的lib也link进项目了。可是`sendAuthRequest`没有收到response。

在`-(void) onResp:(BaseResp*)resp`中加了断点，发现没有进到这个函数。

请问有可能是什么问题呢？

**Comment by yorkie** [comment]
与 https://github.com/weflex/react-native-wechat/issues/84 重复了，关闭了。

**Comment by yorkie** [comment]
@litstrong 签名问题。
