### ISSUE TITLE
iOS RCTLinkingManager.h file not found 

### ISSUE THREAD

**Issue by hk840968883** [weflex/react-native-wechat#106]
iOS RCTLinkingManager.h file not found  这个怎么解决

**Comment by lilongWang** [comment]
我也遇到同样的问题

**Comment by yorkie** [comment]
React-native 的版本报告下？

**Comment by asolas** [comment]
同样的问题，0.31

**Comment by yorkie** [comment]
源码中没有使用到这个文件，所以这个问题是由于项目自身引入 RCTLinkingManager.h 而 "Header Search Paths" 没有更新造成的，解决方案具体参考 @asolas 的评论，不过这里建议改成：

```
$(SRCROOT)/../node_modules/react-native/Libraries/LinkingIOS
```

**Comment by HyperSimon** [comment]
试试这个
```javascript
#import <React/RCTLinkingManager.h> 
```

**Comment by HyperSimon** [comment]
文档该更新了 bro @yorkie

**Comment by Jeijie** [comment]
同样的问题，RN0.59.5，在Header Search Paths加上$(SRCROOT)/../node_modules/react-native/Libraries/LinkingIOS也还是报错

**Comment by Jeijie** [comment]
重新打开XCODE就可以了
