### ISSUE TITLE
升级成RN 0.32 之后安装1.5.5版本不能调起微信登录

### ISSUE THREAD

**Issue by sfrog** [weflex/react-native-wechat#109]
升级之后，iOS和Android都不能调起微信登录，但是分享是可以的。

Android回到1.4.1版本可以正常使用
iOS回到1.4.1版本XCode编译报错

**Comment by sfrog** [comment]
进一步测试发现，iOS上1.4.7和以下版本编译报错，1.5.0和以上版本编译不报错，但是无法调起登录

**Comment by tiensonqin** [comment]
遇到同样的问题，微信登录不能调用,
Android.
RN 0.32, 1.5.3

**Comment by tiensonqin** [comment]
我的问题是wechat里边的sign填的是release的，
更换为debug就可以了。

**Comment by sfrog** [comment]
@tiensonqin 你指的sign是哪里设置的？微信开放平台么？还是项目里

**Comment by tiensonqin** [comment]
微信开放平台

**Comment by sfrog** [comment]
解决了，是因为sendAuthRequest的时候没有传参数，之前的版本是有默认参数的，1.4.4版本把默认参数去掉了，就打不开登录界面，自己传默认参数就好了。见 #60

**Comment by yorkie** [comment]
那关掉了～
