### ISSUE TITLE
调用微信分享时，出现空白“请稍后”页面之后就退出

### ISSUE THREAD

**Issue by cbcye** [weflex/react-native-wechat#110]
调用微信分享时，出现空白“请稍后”页面之后就退出，不能调用微信，RN0.31，Wechat：1.5.5

**Comment by yorkie** [comment]
安卓还是苹果？

**Comment by cbcye** [comment]
Android,问题解决了，谢谢！需要签名APK,使用微信的GenSignature获得签名存储到微信开放平台中，另外使用 react-native run-android --variant=release 用release版本来调用微信

**Comment by tonylkc** [comment]
@yorkie 你好，我已經有做這幾個動作: 
- 生成簽名APK
- 使用微信的GenSignature获得签名存储到微信开放平台中
- 用release版本

可是仍然出現這個情況。我用的是 RN0.37 謝謝

**Comment by yorkie** [comment]
应该还是签名问题，你有QQ么？群里应该有人遇到过这样问题的人挺多的，可以加进去问问看？
