### ISSUE TITLE
微信无法分享图片

### ISSUE THREAD

**Issue by iamzifei** [weflex/react-native-wechat#112]
React Native版本0.33

在手机上调试，APP crash Xcode报错如下：

```
GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: -[__NSCFString absoluteURL]: unrecognized selector sent to instance 0x170308af0
2016-09-20 02:40:01.584984 Fang[4716:1232604] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
2016-09-20 02:40:06.562490 Fang[4716:1232604] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString absoluteURL]: unrecognized selector sent to instance 0x170308af0'
*** First throw call stack:
(0x1907201c0 0x18f15855c 0x190727278 0x190724278 0x19061e59c 0x1906294ac 0x190de0888 0x190d9b2a8 0x190edd6ac 0x190edd5b8 0x1001d6ba4 0x1001d78ac 0x1001d626c 0x190726160 0x190619c3c 0x19061e6ec 0x100069a88 0x1000bb794 0x1000ba9e8 0x1006c125c 0x1006c121c 0x1006c6284 0x1906cdf2c 0x1906cbb18 0x1905fa048 0x19207d198 0x1965d3818 0x1965ce550 0x100028c24 0x18f5dc5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

<img width="1136" alt="screen shot 2016-09-20 at 2 46 46 am" src="https://cloud.githubusercontent.com/assets/399680/18640812/22d84044-7edd-11e6-9e2e-3a1f93fb46df.png">

![img_7191](https://cloud.githubusercontent.com/assets/399680/18664953/388756d8-7f68-11e6-838b-cc270de8caf2.jpg)

Also not sure if this related to `react-native-fs` lib, I use the following version and it worked:
`react-native`: 0.24.1
`react-native-wechat`: 1.4.1
`react-native-fs`: 1.5.1

now with `react-native`:0.33.0 and `react-native-wechat`:1.5.5, I get the above error, doesn't matter if I use `react-native-fs` 1.5.1 or latest version 2.0.1.

The code for sharing image is like the bellowing:

```
      var imagePath = this.props.imageUrl[0]
      if (this.props.wechatShareImage) {
        imagePath = `http://res.cloudinary.com/${serverConfig.cloudinary.cloud_name}/image/sprite/${this.props.wechatShareImage}.png`
      }
      }
      const rootPath = fs.DocumentDirectoryPath
      const savePath = `${rootPath}/wechat-session-share-${_.uniqueId()}.png`
      await fs.downloadFile({ fromUrl: imagePath, toFile: savePath})
      const result = await WeChat.shareToSession({
        type: 'imageFile',
        title: 'image file download from network',
        description: shareText,
        mediaTagName: 'email signature',
        messageAction: undefined,
        messageExt: shareText,
        imageUrl: `file://${savePath}` // require the prefix on both iOS and Android platform
      })
```

**Comment by iamzifei** [comment]
把RCTWechat.m的226行
`NSURLRequest *imageRequest = [NSURLRequest requestWithURL:aData[RCTWXShareImageUrl]];`
改成了
`NSURLRequest *imageRequest = [NSURLRequest requestWithURL:[NSURL URLWithString:aData[RCTWXShareImageUrl]]];`

很奇怪之前issue #94 解决了为什么现在又有这个问题

**Comment by yorkie** [comment]
你的 react-native-wechat 版本是1.4.1，试试最新版的？

**Comment by iamzifei** [comment]
我package.json用的是最新版的。也npm install过了。奇怪，我回去再验证下。






On Wed, Sep 21, 2016 at 10:50 AM +1000, "Yorkie Liu" <notifications@github.com> wrote:












你的 react-native-wechat 版本是1.4.1，试试最新版的？

**Comment by yorkie** [comment]
Try with v1.6.1 :)
