### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by hanwufeidadi** [weflex/react-native-wechat#115]
我有一个Android工程，嵌入了react native代码，然后整合微信接入，按照文档的步骤，一步一步弄下来，修改完gradle文件后，同步，报Configuration with name 'default' not found错误，

**Comment by yorkie** [comment]
最好给出更具体的一些信息来，这样方便查看问题，另外建议再检查下你的 gradle 的配置文件～

**Comment by hanwufeidadi** [comment]
我是这么做得：
先在项目的根目录下执行命令：npm install react-native-wechat --save下载
然后配置setting.gradle文件如下：
- include ':app'
include ':RCTWeChat'
project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat/android')

再设置app下的build.gradle文件，如下：
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile "com.facebook.react:react-native:+"
    compile files('libs/pushservice-5.2.0.12.jar')
    compile files('libs/Baidu_MobAds_SDK.jar')
    compile project(':RCTWeChat')
}

修改gradle文件后，点击“Sync Now” 就报这个错误

**Comment by hanwufeidadi** [comment]
自己把这个问题解决了，工程引用目录不对，把include ':RCTWeChat' project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat/android')
换为下面的就可以：
project(':RCTWeChat').projectDir = new File(settingsDir, './node_modules/react-native-wechat/android')

**Comment by hanwufeidadi** [comment]
现在在AndroidStudio中编译通过了，但是写测试代码时报错：undefined is not an object(evaluating 'WeChat.registerApp')
测试代码如下：
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  ToastAndroid,
} from 'react-native';
var WeChat=require('react-native-wechat');
//import fs from 'react-native-fs';
class CustomButton extends Component {
  render() {
    return (
      <TouchableHighlight
        style={styles.button}
        underlayColor="#a5a5a5"
        onPress={this.props.onPress}>
        <Text style={styles.buttonText}>{this.props.text}</Text>
      </TouchableHighlight>
    );
  }
}
class HelloWorld extends Component {


  render() {
    return (
      <View style={{margin:20}}>
        <Text style={styles.welcome}>
            微信好友/朋友圈分享实例
        </Text>
        <CustomButton text='微信好友分享-文本'
          onPress={() => {
                  WeChat.isWXAppInstalled()
                    .then((isInstalled) => {
                      if (isInstalled) {
                        console.log('haha,test');
                        WeChat.shareToSession({type: 'text', description: '测试微信好友分享文本'})
                        .catch((error) => {
                          console.log(error.message);
                        //  ToastShort(error.message);
                        });
                      } else {
                        ToastShort('没有安装微信软件，请您安装微信之后再试');
                      }
                    });
              }}
        />
        <CustomButton text='微信好友分享-链接'
          onPress={() => {
                  WeChat.isWXAppInstalled()
                    .then((isInstalled) => {
                      if (isInstalled) {
                        WeChat.shareToSession({
                          title:'微信好友测试链接',
                          description: '分享自:江清清的技术专栏(www.lcode.org)',
                          thumbImage: 'http://mta.zttit.com:8080/images/ZTT_1404756641470_image.jpg',
                          type: 'news',
                          webpageUrl: 'http://www.lcode.org'
                        })
                        .catch((error) => {
                          console.log(error.message);
                        //  ToastShort(error.message);
                        });
                      } else {
                        console.log('没有安装微信软件');
                      //  ToastShort('没有安装微信软件，请您安装微信之后再试');
                      }
                    });
              }}
        />
        <CustomButton text='微信朋友圈分享-文本'
          onPress={() => {
                  WeChat.isWXAppInstalled()
                    .then((isInstalled) => {
                      if (isInstalled) {
                        WeChat.shareToTimeline({type: 'text', description: '测试微信朋友圈分享文本'})
                        .catch((error) => {
                          ToastShort(error.message);
                        });
                      } else {
                        ToastShort('没有安装微信软件，请您安装微信之后再试');
                      }
                    });
              }}
        />
        <CustomButton text='微信朋友圈分享-链接'
          onPress={() => {
                  WeChat.isWXAppInstalled()
                    .then((isInstalled) => {
                      if (isInstalled) {
                        WeChat.shareToTimeline({
                          title:'微信朋友圈测试链接',
                          description: '分享自:江清清的技术专栏(www.lcode.org)',
                          thumbImage: 'http://mta.zttit.com:8080/images/ZTT_1404756641470_image.jpg',
                          type: 'news',
                          webpageUrl: 'http://www.lcode.org'
                        })
                        .catch((error) => {
                          ToastShort(error.message);
                        });
                      } else {
                        ToastShort('没有安装微信软件，请您安装微信之后再试');
                      }
                    });
              }}
        />
      </View>
    );
  }

    componentDidMount() {//React组件的一个生命周期方法，组件加载完后调用。
        WeChat.registerApp('wx8d560da3ba038e7e');
     }
}
const styles = StyleSheet.create({

  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  button: {
    margin:5,
    backgroundColor: 'white',
    padding: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#cdcdcd',
  },
});

AppRegistry.registerComponent('HelloWorld', () => HelloWorld);

**Comment by yorkie** [comment]
辛苦了，能否把你上面一段评论整理一下格式，这样方便之后遇到同样问题的同学观看，或者是你提交成PR，可以考虑加到README里面去。
