### ISSUE TITLE
Scope 参数错误或没有 Scope权限

### ISSUE THREAD

**Issue by litingjun2015** [weflex/react-native-wechat#122]
您好：

我已在微信开放平台申请应用并获得“微信登录”接口。

```
WeChat.sendAuthRequest('snsapi_userinfo')
      .then((result)=>{
        console.log(result)
```

以上调用会返回 001ndnB72xQOON0wBHC724rlB72ndnBN 这样的字符串。

我想获得用户的openid，尝试下面的调用：

```
WeChat.sendAuthRequest('snsapi_base')
          .then((result)=>{
            console.log(result)
          })
          .catch((e)=>{
            console.error(e);
          })
```

结果报“Scope 参数错误或没有 Scope权限”。请问是什么原因？

谢谢！

**Comment by yorkie** [comment]
snsapi_base是静默授权，你应该需要去微信后台申请。

**Comment by litingjun2015** [comment]
您好，我在微信开放平台的移动应用已经获得“微信登录”接口权限：

![wechat](https://cloud.githubusercontent.com/assets/13675353/19583150/dc90ed5e-976c-11e6-8bc5-f230c8627b3d.png)

请问还需要申请什么权限？

**Comment by yorkie** [comment]
你那边能抓个包么？userinfo应该会返回对象来着～

**Comment by litingjun2015** [comment]
您好，

我的测试代码如下：

```
async componentDidMount() {
    try {
      await WeChat.registerApp('wx8ce2e64af40f....');
      this.setState({
        apiVersion: await WeChat.getApiVersion(),
        wxAppInstallUrl: await WeChat.getWXAppInstallUrl(),
        isWXAppSupportApi: await WeChat.isWXAppSupportApi(),
        isWXAppInstalled: await WeChat.isWXAppInstalled()
      });
      console.log('state', this.state);

      console.log('sendAuthRequest', typeof WeChat.sendAuthRequest);

    } catch (e) {
      console.error(e);
    }
    console.log('WeChat', WeChat);


……

_sendAuthRequest() {

     WeChat.sendAuthRequest('snsapi_userinfo')
      .then((result)=>{
        console.log('sendAuthRequest("snsapi_userinfo") result', result)

        WeChat.sendAuthRequest('snsapi_base')
          .then((result)=>{
            console.log('sendAuthRequest("snsapi_base") result', result)
          })
          .catch((e)=>{
            console.error(e);
          })


      })
      .catch((e)=>{
        console.error(e);
      })
  }
```

chrome的调试输出截屏如下：
![chrome_debug](https://cloud.githubusercontent.com/assets/13675353/19587952/ee7bc322-9794-11e6-86a4-cbf497aae1f0.png)


用wireshark 抓包没有看到信息
`http && (ip.src == 192.168.31.241 || ip.dst == 192.168.31.158)`

WeChat.sendAuthRequest('snsapi_userinfo') 返回的就是一个字符串，您指的userinfo返回对象应该如何操作？

**Comment by yorkie** [comment]
可以不要重复多次的调用`sendAuthRequest`，分开测试呢？

**Comment by litingjun2015** [comment]
您好，分开测试单单调用 WeChat.sendAuthRequest('snsapi_base') 也是出现“Scope 参数错误或没有 Scope权限”页面。

您那边有没有可供测试的AppId借我测一下不知是否方便？ 我的qq： 20320106
gmail： tingjun.li

**Comment by maige123** [comment]
我的也是，返回了一个字符串，是code字符串么？

**Comment by maige123** [comment]
@litingjun2015 我看了下，返回的是code，然后你必须通过code去微信换取open_id,这样才可以。
文档：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317853&token=094c5fa2119eb900480cbe98c13c12b09cd58285&lang=zh_CN

![image](https://cloud.githubusercontent.com/assets/7948820/19595730/e8b91128-97bd-11e6-8b94-bdb620bd8c56.png)

**Comment by litingjun2015** [comment]
@maige123 非常感谢！ 我今天试一下。

**Comment by litingjun2015** [comment]
@maige123 能取到openid了，谢谢！

**Comment by maige123** [comment]
@litingjun2015  不客气

**Comment by santong** [comment]
可以一次传两个参数吗 我传arrary进去 会提示参数错误

**Comment by yorkie** [comment]
嗯呢 你可以自己把参数拼成一个字符串，我以前一般是拼了转base64传，你可以试试～
