### ISSUE TITLE
Android打包发布的时候报错

### ISSUE THREAD

**Issue by xiaomilii** [weflex/react-native-wechat#125]
调试的时候没有问题，但是正式打包发布的时候报错
![image](https://cloud.githubusercontent.com/assets/18210277/19617436/c3184ace-9862-11e6-8c79-451daf67bfcc.png)

@yorkie 求助大神
代码混淆也添加了
![image](https://cloud.githubusercontent.com/assets/18210277/19617417/6d15e866-9862-11e6-9e21-ca0a272bd80b.png)

**Comment by yorkie** [comment]
你用红色圈圈出来的部分属于warning，不影响正常的发布吧？
