### ISSUE TITLE
react-native run-android warning Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by litingjun2015** [weflex/react-native-wechat#127]
react-native -v
react-native-cli: 1.0.0
react-native: 0.35.0

> DuangLink-MacBook-Pro:bizapp3 duanglink$ npm install react-native-wechat --save
bizapp@0.0.1 /Users/duanglink/ReactNativeProjects/bizapp3
└─┬ react-native-wechat@1.7.0
  ├─┬ es6-promisify@3.0.0
  │ └── es6-promise@3.3.1
  └── events@1.0.2

> :app:preDexDebug
Unknown source file : warning: Ignoring InnerClasses attribute for an anonymous inner class
Unknown source file : (com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
Unknown source file : associated EnclosingMethod attribute. This class was probably produced by a
Unknown source file : compiler that did not target the modern .class file format. The recommended
Unknown source file : solution is to recompile the class from source, using an up-to-date compiler
Unknown source file : and without specifying any "-target" type options. The consequence of ignoring
Unknown source file : this warning is that reflective operations on this class will incorrectly
Unknown source file : indicate that it is *not* an inner class.
Unknown source file : warning: Ignoring InnerClasses attribute for an anonymous inner class
Unknown source file : (com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
Unknown source file : associated EnclosingMethod attribute. This class was probably produced by a
Unknown source file : compiler that did not target the modern .class file format. The recommended
Unknown source file : solution is to recompile the class from source, using an up-to-date compiler
Unknown source file : and without specifying any "-target" type options. The consequence of ignoring
Unknown source file : this warning is that reflective operations on this class will incorrectly
Unknown source file : indicate that it is *not* an inner class.
Unknown source file : warning: Ignoring InnerClasses attribute for an anonymous inner class
Unknown source file : (com.tencent.mm.sdk.b.b) that doesn't come with an
Unknown source file : associated EnclosingMethod attribute. This class was probably produced by a
Unknown source file : compiler that did not target the modern .class file format. The recommended
Unknown source file : solution is to recompile the class from source, using an up-to-date compiler
Unknown source file : and without specifying any "-target" type options. The consequence of ignoring
Unknown source file : this warning is that reflective operations on this class will incorrectly
Unknown source file : indicate that it is *not* an inner class.

**Comment by yorkie** [comment]
Which tools do you use to generate the logs?

**Comment by litingjun2015** [comment]
@yorkie when I run `react-native run-android`

**Comment by yorkie** [comment]
Warnings is not error, thus it doesn't effect your app. And after researching the above logs, it seems to detect the WeChat SDK source problems.
