### ISSUE TITLE
微信支付结果监听没有成功

### ISSUE THREAD

**Issue by IOSrobert** [weflex/react-native-wechat#128]
componentWillMount() {
    //  处理支付回调结果
    wechat.addListener('finishedPay', (res) => {
      console.log('==event', res);
      if (res.errCode === 0) {
        console.log('===支付成功');
      } else if (res.errCode === -1) {
        console.log('===支付失败,请稍后尝试');
      } else if (res.errCode === -2) {
        console.log('===支付取消');
      }
    });
}
代码如上，可以支付成功，也可以跳转回来。上面的打印一个都没有执行

**Comment by yorkie** [comment]
"finishedPay"事件不存在，使用"PayReq.Resp"试试，另外你哪里得到"finishedPay"的？

**Comment by IOSrobert** [comment]
都试过了，最后选择了支付方法返回的promise实现的监听

**Comment by cnpmge** [comment]
> 都试过了，最后选择了支付方法返回的promise实现的监听

请问能看下具体写法吗？怎么实现promise实现监听？
