### ISSUE TITLE
你好！问一个分享朋友圈的问题

### ISSUE THREAD

**Issue by jlala** [weflex/react-native-wechat#129]
我的应用修改过 开机动画，是使用了图片。
我把 lanuchscreen 移除了。
但是我分享朋友圈以后 rn程序还是跳转到 lanuchscreen了 然后就奔溃了 
请问这个怎么解决呢？

**Comment by yorkie** [comment]
这个可能是缓存问题？安卓还是iOS？

**Comment by jlala** [comment]
ios的

**Comment by yorkie** [comment]
你试试看把项目的一些安装文件清理一下，再重新安装一次试试看？

**Comment by jlala** [comment]
装了呢 并且就是 ip6 ios10 有问题  ip6p ip5 没问题

**Comment by yorkie** [comment]
问题解决了吗？@jiala
