### ISSUE TITLE
Possible Unhandled Promise Rejection(id:2): can not find variable:toastShort

### ISSUE THREAD

**Issue by NextChampion** [weflex/react-native-wechat#132]
调用分享方法的时候 就回提示这个Warning,请问是哪里出了问题啊?

**Comment by maige123** [comment]
没有导入库，toastShort是一个库。
react-native-root-toast

地址：https://github.com/magicismight/react-native-root-toast

**Comment by yorkie** [comment]
这个错误是由其他例子引起的，所以把这个关掉了～
