### ISSUE TITLE
wechat login have question

### ISSUE THREAD

**Issue by JasonStu** [weflex/react-native-wechat#133]
I move to wechat login View !but I Click login have no response! i See IOS '-(void) onResp:(BaseResp*)resp'had  don't run ! this is my code `   WeChat.sendAuthRequest("snsapi_userinfo", "myclient_wx_login")
      .then((result) => {
        console.log(result)
      })
      .catch((e) => {
        console.error(e);
      })`
i saw #84 can't fix my question!

**Comment by yorkie** [comment]
Please resign your app and try again

**Comment by JasonStu** [comment]
now fix ! THX!!

**Comment by unordered** [comment]
how do you solve this problem, My situation is the same as yours.
