### ISSUE TITLE
分享之后的回调是什么

### ISSUE THREAD

**Issue by lennyup** [weflex/react-native-wechat#135]
比如说 分享取消 分享失败 以及分享成功 求解

**Comment by yorkie** [comment]
现在不支持回调的方式获取分享，需要用事件：https://github.com/weflex/react-native-wechat#sendmessagetowxresp

**Comment by lennyup** [comment]
SendAuth.Resp　这是什么　有点看不懂　以及后面那个　能稍微解释下吗 @yorkie

**Comment by yorkie** [comment]
`SendAuth.Resp`: 登录成功后触发
`SendMessageToWX.Resp`: 分享成功后触发

**Comment by sumyfly** [comment]
您好，我在Android登录时，没有跳出APP，也没有在onResp()得到结果。但是api.sendReq(req)返回true。我的签名是对的，我确认过了。请问还有那种可能出问题？

**Comment by yorkie** [comment]
```es
wechat.sendAuthRequest(...);
wechat.addEventListener('SendAuth.Resp', (...args) => {
  // 这里是回调
});
```
