### ISSUE TITLE
配置完之后react-native run-android报错

### ISSUE THREAD

**Issue by jinleli** [weflex/react-native-wechat#137]
你好：
        我按照教程配置完android之后报下面图片上的错，麻烦帮我看看，谢谢！
![image](https://cloud.githubusercontent.com/assets/20489071/20296956/daf9c4bc-ab48-11e6-9052-76e470f1581c.png)

**Comment by jinleli** [comment]
我在安装这个库的时候报错了，如下图，和这个有关系吗？
![image](https://cloud.githubusercontent.com/assets/20489071/20297092/aa90cfd6-ab49-11e6-8942-1060f834dbad.png)

**Comment by yorkie** [comment]
你这个可能是 Windows 安装的问题，跟这个库本身没有问题，可以试试给 Node.js 提一个 issue
