### ISSUE TITLE
undefined is not a function(evaluating 'Wechat.registerApp')

### ISSUE THREAD

**Issue by alukaka** [weflex/react-native-wechat#143]
when i use it then show this!!

undefined is not a function(evaluating 'Wechat.registerApp('***********'))

what should i do?

**Comment by yorkie** [comment]
What's your `import` statement for this module?

**Comment by alukaka** [comment]
import * as WeChat from 'react-native-wechat'

**Comment by yorkie** [comment]
try `WeChat.registerApp`

**Comment by alukaka** [comment]
我 把   WeChat  log 出来，可是WeChat是个空的对象，我在里面并没有找到这个方法

**Comment by yorkie** [comment]
Try `console.log(WeChat)` again? Thanks :)

**Comment by alukaka** [comment]
Objectdefault: Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()

**Comment by yorkie** [comment]
It seems that your react-native-wechat doesn't get installed correctly, please reinstalled and try again.

**Comment by alukaka** [comment]
i had try again more....
nothing happened!!
QAQ

**Comment by yorkie** [comment]
Try with v1.8.0?

**Comment by alukaka** [comment]
nothing is  change!

**Comment by yorkie** [comment]
I dunno, too, it works for me....Please find a way to reproduce this bug in any machine, thanks :)

**Comment by alukaka** [comment]
import * as WeChat from '../../../node_modules/react-native-wechat'
use  this  can success
