### ISSUE TITLE
安卓根本用不了啊

### ISSUE THREAD

**Issue by ouyangdxq** [weflex/react-native-wechat#146]
在安卓真机上，如果没有登录微信在react调用会跳到微信登录界面，但是如果微信已经登录了，react调用分享回一闪而过并且log打印分享成功，但是分享其实是失败的

**Comment by yorkie** [comment]
签名问题，可以在官群问问其他人～

**Comment by ouyangdxq** [comment]
是的，签名造成的问题

**Comment by yorkie** [comment]
那关啦哈～
