### ISSUE TITLE
It doesn't work in the real iPhone6s

### ISSUE THREAD

**Issue by oknixus** [weflex/react-native-wechat#15]
This is in tdzl2003
![image](https://cloud.githubusercontent.com/assets/4592706/12031323/8e968232-ae45-11e5-94d9-c9c6c5a4d671.png)

**Comment by tdzl2003** [comment]
This is because the sdk included by this package should be upgrade.

Currently, you can fix by modify setting of RCTWeChat, change `Enable Bitcode` to `No`.

![image](https://cloud.githubusercontent.com/assets/3185808/12032300/8dacebde-ae51-11e5-8289-b0186be01693.png)

**Comment by tdzl2003** [comment]
@yorkie 我们需要更新下iOS版的微信SDK

**Comment by yorkie** [comment]
> This is because the sdk included by this package should be upgrade.

@tdzl2003 有文档之类的引用么？

**Comment by yorkie** [comment]
@NixusCN 可否试试最新的1.2.1是否解决你的问题？

**Comment by NixusCN** [comment]
@yorkie 两个错误：
![image](https://cloud.githubusercontent.com/assets/4592706/12059971/e6c6aba6-afa0-11e5-999b-377769404880.png)
![image](https://cloud.githubusercontent.com/assets/4592706/12060004/ed800a1e-afa0-11e5-9424-c6bc82bd1b37.png)
![image](https://cloud.githubusercontent.com/assets/4592706/12060006/f8832c7a-afa0-11e5-98f5-9331a8aeaab4.png)
是我姿势不对吗？

**Comment by yorkie** [comment]
这个是因为这两个文件中使用了UIKit中的类，已经更新到 v1.2.3 解决了这个问题～ 不好意思 @NixusCN 最近团队工作很忙，所以处理外部 issue 会慢一些

**Comment by yhdevelop** [comment]
修改了以下两个方法，分享后能正常返回
`- (instancetype)init
{
    self = [super init];
    if (self) {
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleOpenUrl:) name:@"RCTOpenURLNotification" object:nil];
    }
    return self;
}`
`- (BOOL)handleOpenUrl:(NSNotification *)notifi
{
    NSDictionary *userInfo = notifi.userInfo;
    NSString *url = [userInfo objectForKey:@"url"];
    NSURL *aUrl = [NSURL URLWithString:url];
    
    if ([WXApi handleOpenURL:aUrl delegate:self])
    {
        return YES;
    }
    return NO;
}`
