### ISSUE TITLE
Android Pay promise not resolving

### ISSUE THREAD

**Issue by eulo** [weflex/react-native-wechat#150]
iOS is working fine, and I've got Android pay completing but the PayResp isn't firing.

```javascript
async pay(options) {
  try {
    // Hangs forever
    result = await WeChat.pay(options);
  } catch (error) { }
  return result;
}
```

I feel like it's an issue with **WXEntryActivity**, but I can't work it out.
I've added /android/app/src/main/java/com/app/wxapi/WXEntryActivity.java
And linked it in the AndroidManifest, but the responses don't seem to be coming through.

```xml
<application
  android:name=".MainApplication"
  android:allowBackup="true"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:theme="@style/AppTheme">

  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:launchMode="singleTop"
    android:screenOrientation="portrait"
    android:configChanges="keyboard|keyboardHidden|screenSize">
    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
  </activity>

  <activity
    android:name=".wxapi.WXEntryActivity"
    android:label="@string/app_name"
    android:exported="true"/>

</application>
```

Is there something really dumb I've missed?

**Comment by sorcerdu** [comment]
rename "WXEntryActivity" to "WXPayEntryActivity"。

https://www.google.com.hk/search?q=WXPayEntryActivity+WXEntryActivity&client=pub-1895553756377946&channel=9593578544&forid=1&prog=aff&hl=zh-CN&gws_rd=ssl

**Comment by eulo** [comment]
Perfect, thank you.

**Comment by xiaomilii** [comment]
@eulo How to solve this problem？

**Comment by FaiChou** [comment]
Saved my day.
