### ISSUE TITLE
error for android

### ISSUE THREAD

**Issue by combing520** [weflex/react-native-wechat#151]
I just do as  the guidance you give ,but I  got the error  result .( My OS is Android)
'' undefined is not an object (evaluating 'f.default.registerApp') ''

**Comment by combing520** [comment]
My  PC ‘s  OS is Win ，  in  the  Atom ,  I can  import 'react-native-wechat' , and  it don't show error, 

the  error  statement    is  ' componentDidMount(){
      Wechat.registerApp('wx22f08d5a9d1eff1a');
  }
'

**Comment by yorkie** [comment]
Could you please print the `Wechat` object before calling registerApp?
