### ISSUE TITLE
'RCTImage/RCTImageUtils.h' can not found when archiving release package, but it's ok when debugging.

### ISSUE THREAD

**Issue by jaggerwang** [weflex/react-native-wechat#162]
### Problems

I found the 'RCTImage' directory not exist in the Xcode cache directory '~/Library/Developer/Xcode/DerivedData/zaiqiuchang-fwykrwmotbpozgegbmtywbczscln/Build/Products/Debug-iphonesimulator/include', it needs to be created manually and copy 'RCTImageUtils.h' from RN source to there when debugging. But I don't know where to modify when archiving release package.

It can be build when removed 'RCTImage/RCTImageUtils.h' import in RCTWeChat.m, and can share to WeChat. So why import this file?

![image](https://cloud.githubusercontent.com/assets/1255011/22059532/294258c8-dda8-11e6-9c90-44b267c8362d.png)

### Env
react-native: 0.40.0
react-native-wechat: newest from GitHub
platform: iOS 10.2, Xcode 8.2.1

**Comment by gameboyVito** [comment]
I have the same issue. My dev environment:
react-native: 0.42-rc.3
iOS, Xcode 8.2.1

**Comment by jaggerwang** [comment]
Just remove 'RCTImage/RCTImageUtils.h' to fix.

**Comment by bluedusk** [comment]
Did you fixed this problem ?

**Comment by Richard-Cao** [comment]
fixed
