### ISSUE TITLE
android 授权后无返回结果

### ISSUE THREAD

**Issue by sunny20131314** [weflex/react-native-wechat#165]
Hello！

微信分享正常，
在微信登录时，android的release版本，正常调起微信登录页，但授权后无返回结果（没有alert）

代码如下：
        try {
          res = await WeChat.sendAuthRequest('snsapi_userinfo');
          alert(res);
        }
        catch (e) {
          alert(e);
        }

相关版本号：
"react": "^15.4.1",
"react-native": "^0.39.2",
"react-native-wechat": "^1.8.0",

设备： 
华为荣耀8 
 android 版本： 6.0

**Comment by yorkie** [comment]
是不是没有创建：WXEntryActivity 呢？按照 [linking-android-with-gradle](https://github.com/weflex/react-native-wechat#linking-android-with-gradle) 确认下！

**Comment by sunny20131314** [comment]
谢谢回复~~~
 WXEntryActivity已经创建了
![image](https://cloud.githubusercontent.com/assets/13795567/22764051/458b4bdc-eea3-11e6-9a81-920144db4e4a.png)

AndroidManifest.xml 中也配置了
![image](https://cloud.githubusercontent.com/assets/13795567/22764380/4b076cf6-eea5-11e6-80dc-fbbf3249c5e6.png)

烦请大神指导下

**Comment by sunny20131314** [comment]
即使配置了，依然没有任何返回结果, 不管是执行成功还是执行失败为啥都没有触发啊...

**Comment by sunny20131314** [comment]
最终找到原因，是因为package name 和 applicaionid 不一致[#84](https://github.com/weflex/react-native-wechat/issues/84)  。

**Comment by xuyuanzhou** [comment]
你所指的package name 和 applicaionid 不一致是对于android项目哪个文件里的

**Comment by Vinkugor** [comment]
@sunny20131314 请问applicaionid是在那里配置的呢？

**Comment by renrenguiwei** [comment]
same problem, can open the wechat, but no response
