### ISSUE TITLE
Android在前端发起支付一闪而过,errCode返回-1

### ISSUE THREAD

**Issue by lizhiren2016** [weflex/react-native-wechat#171]
Android在前端发起支付一闪而过,errCode返回-1，搞死我了，签名我也使用微信的校验工具校验过了，appID更加没写错，也清理过微信数据缓存，一样都没效果。求租下社区的大神，谁遇到过类似的问题，或有什么经验指点一下！感激不敬！！

**Comment by lizhiren2016** [comment]
该库现在没有人维护吗？？？

**Comment by yorkie** [comment]
可以加QQ官方群里问问～？

**Comment by lizhiren2016** [comment]
@yorkie 您好，请问下QQ群是多少？方便说一下嘛

**Comment by yorkie** [comment]
336021910

**Comment by janiokq** [comment]
我也遇到了一样的 问题  你已经解决了吗 @lizhiren2016

**Comment by zhuangchuming** [comment]
有类似的问题，请问有解决吗 @janiokq @lizhiren2016

**Comment by janiokq** [comment]
我这边是后台给签名有问题 @zhuangchuming

**Comment by zhuangchuming** [comment]
请问你现在的react-native版本是多少呢 @janiokq

**Comment by yorkie** [comment]
问题应该已经解决了吧～

**Comment by 452MJ** [comment]
+1

**Comment by 452MJ** [comment]
@lizhiren2016 哥你是怎么解决的
