### ISSUE TITLE
shareToTimeline分享后的promise的then和catch都没调用

### ISSUE THREAD

**Issue by CecilLee** [weflex/react-native-wechat#173]
```javascript
wechat.shareToTimeline(data)
.then(ret=>{
 console.log(ret);
})
.catch(err=>{
 console.log(err);
});
```

无论是then和catch都没被调用，是怎么回事。

**Comment by yorkie** [comment]
有跳转到微信应用吗？

**Comment by CecilLee** [comment]
有跳转，分享也成功了，就是跳回app后，没有进入then和catch

**Comment by yorkie** [comment]
那可能是以下原因导致的：

1. 签名问题
2. Entry配置有问题

**Comment by CecilLee** [comment]
ios下Entry怎么配置

**Comment by yorkie** [comment]
https://github.com/weflex/react-native-wechat#linking-ios 里面的AppDelegate

**Comment by CecilLee** [comment]
AppDelegate已经设置了，而且我用Linkng.addEventListener('url',fn)来监控自己的app被唤起的事件
事件被正常触发，参数为：
"wx2a1e3ad1a1fb2722://platformId=wechat"


我看例子是用的await的写法调用的，难道是我的promise的写法不兼容， 必须改用async/await??

**Comment by yorkie** [comment]
应该是的吧 promise的用法相对还是比较复杂的，能用async/await最好，先关掉了～
