### ISSUE TITLE
登录授权成功后无回调

### ISSUE THREAD

**Issue by Jasonellen** [weflex/react-native-wechat#175]
WeChat.isWXAppInstalled()
            .then((is) => {
              if(is){
                WeChat.sendAuthRequest('snsapi_userinfo')
                  .then((data) => {
                    console.log(data)
                  })
                 .catch((err) => {
                    console.log(err)
                 })
              }
            })   授权后调回APP怎么这两个回调都没有执行啊，分享功能是可以的..

**Comment by HyperSimon** [comment]
@Jasonellen 请问是怎么解决的？

**Comment by Kennytian** [comment]
@Jasonellen 请问是怎么解决的？

**Comment by rabbitzbx** [comment]
@Jasonellen 请问事怎么解决的？
