### ISSUE TITLE
react-native@0.42版本，android， import 之后会崩溃

### ISSUE THREAD

**Issue by hitbear518** [weflex/react-native-wechat#176]
```javascript
import * as Wechat from 'react-native-wechat'
```
之后，会出现 
`undefined is not a function (evaluating 'globalObject.haOwnProperty("Promise")')`
程序崩溃，
ios 正常

**Comment by hitbear518** [comment]
好像是 es6-promisify 导致的……

**Comment by hitbear518** [comment]
我 fork 了一份，使用 bluebird 的 promisify 之后不再崩溃了。
我自己的使用的 api （登录和shareToSession）没有问题，但是不确定这么改会不会影响到其他 api，
暂时没 pr 回来。

**Comment by 3610cn** [comment]
确实有这个问题，升级到42以后android一直跑不起来，调试发现是es6-promisify的问题

**Comment by zhuangchuming** [comment]
同样的问题。

**Comment by don-qdjs** [comment]
除了引入其他promiss，还有其他办法否？

**Comment by the-ant** [comment]
同这个问题了 https://github.com/mockingbot/react-native-zip-archive/issues/27

**Comment by bugmover** [comment]
题主能说下这个问题的解决方法吗，才接触rn

**Comment by hitbear518** [comment]
@bugmover 
> 我 fork 了一份，使用 bluebird 的 promisify 之后不再崩溃了。
我自己的使用的 api （登录和shareToSession）没有问题，但是不确定这么改会不会影响到其他 api，

就是用 bluebird 的 promisify 替换了原来的同名方法

**Comment by zhuangchuming** [comment]
@hitbear518 你好，替换的是哪里的呢，就是react-native下面的promise吗

**Comment by byk04712** [comment]
![wx20170310-175836](https://cloud.githubusercontent.com/assets/6211302/23790732/50ab8d86-05bb-11e7-9f4d-8b97896223b6.png)

我也遇到同样问题了，在Debug JS Remotely 模式下却正常，求解决！

**Comment by hitbear518** [comment]
@zhuangchuming 我看不懂你的错误报告……
你可以先依赖我 fork 的版本，应该就可以 build 成功了

**Comment by zhuangchuming** [comment]
@hitbear518 好的，我那个不是错误报告哦，是react-native-wechat的package.json文件，里面我把"dependencies": 的es6-promisify给去掉了，是不是还需要编译什么的？

**Comment by zhuangchuming** [comment]
@hitbear518 npm 好像不能下载依赖你的fork：
npm install hitbear518/react-native-wechat --save

**Comment by zhuangchuming** [comment]
@hitbear518   我直接用你的文件替换我本地的文件，然后安装 bluebird，使用的是微信支付，会报警告，然后直接返回了微信的回调。ios正常，微信支付不能使用。

**Comment by hitbear518** [comment]
@zhangweijie-cn 
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by zhuangchuming** [comment]
你能调得起微信支付吗 @hitbear518

**Comment by hitbear518** [comment]
@zhuangchuming 
我没有用到，所以没有试

**Comment by zhuangchuming** [comment]
@hitbear518 微信支付是可以使用的，没问题。你修改了那个，React/RCTImageUtils.h的头文件我这边也是会找不到，所以我注释掉了

**Comment by yorkie** [comment]
https://github.com/weflex/react-native-wechat/pull/189 看看这个PR能否解决掉这个问题？

**Comment by hitbear518** [comment]
@yorkie 应该不能吧……当时我试过升级 es6-promisify 到最新版

**Comment by yorkie** [comment]
给一个示例代码，我这里编译是可以的～

**Comment by jjzxt** [comment]
es6-promisify升级到5.0.0了,还是不行

**Comment by hitbear518** [comment]
@yorkie 
https://github.com/hitbear518/RNWechatBug
我新建了一个空的 RNProject，依赖了自己 fork 的 react-native-wechat（把 es6-promisify 升级到了5.0.0），然后 import * as Wechat from 'react-native-wechat'，可以稳定重现 bug

**Comment by flavordaaave** [comment]
@hitbear518 Your solution is working for me. But we could also try to remove the browserify dependency completely. I've done that for the react-native-weibo already:
https://github.com/reactnativecn/react-native-weibo/pull/28

**Comment by lifuzu** [comment]
@flavordaaave good solution, awesome! could you please make the same for this repo?

**Comment by hitbear518** [comment]
@yorkie 
I removed promisify to fix this and made a pr #194 ,
but I only tested registerApp, isWXInstalled, sendAuthRequest, shareToSession;

and there's some extra diff because of yarn and prettier,

what should I do next?

**Comment by yorkie** [comment]
尝试一下 1.9.2 版本 :)
