### ISSUE TITLE
sharetotimeline调用疑惑

### ISSUE THREAD

**Issue by Choicelin** [weflex/react-native-wechat#179]
我的app登录时会注册appid（registerApp），但是调用sharetotimeline时会产生需要注册问题 （registerApp required），但是当我在我的分享组件中再注册一次就会报appid问题，说NSDictionary  can not convert to NSString，是什么原因呢

**Comment by Choicelin** [comment]
您好，现在再次注册一次，可以成功分享，但是会报app is already registered，如果去掉注册app再分享又会有registerApp required，

**Comment by Choicelin** [comment]
现在我把注册写到全局，解决了之前的问题，但是分享后回到app会报Possible Unhandled Promise Rejection(id:0)问题

**Comment by Choicelin** [comment]
fixed，由于await没写的原因

**Comment by ResponseState200** [comment]
@Choicelin 您好,我现在跟您报一样的错,你说由于await没写???我不太明白,能否让我看一下你的代码示例,谢谢

**Comment by Choicelin** [comment]
@ResponseState200 Hi there!I cannot find my code now.Some apis of this sdk return a Promise so you have to await them.I'm not quite sure whether you know async await syntax.If you don't, just read about it.

**Comment by ResponseState200** [comment]
`        let result = await wechat.shareToTimeline({
               thumImage:"http://www.ncloud.hk/email-signature-262x100.png",
               type: 'imageUrl',
               title: 'web image',
               description: 'share web image to time line',
               mediaTagName: 'email signature',
               messageAction: undefined,
               messageExt: undefined,
               imageUrl: 'http://www.ncloud.hk/email-signature-262x100.png'
           });`

写了之后依然调用不起来,分享文字是正常的,图片就会毫无反应,也不报错.
