### ISSUE TITLE
ios支付完成后，点击返回应用，返回微信的主页

### ISSUE THREAD

**Issue by zhuangchuming** [weflex/react-native-wechat#180]
支付完成后无法回调到应用上，这个是正常现象吗？

**Comment by zhuangchuming** [comment]
ios 的url type 问题，现在已解决

**Comment by 94cstyles** [comment]
url type是指什么 能否给我说说~ 我微信登录都可以成功返回

**Comment by LSL1618** [comment]
同支付无回调，then和catch都不执行，但又能调起并完成支付，就是不回调。

**Comment by liuqiiiiiii** [comment]
我也遇到了这个问题，ios支付成功后直接返回微信主界面，而不是APP。
并且，APP会一直卡在支付界面，只能结束APP进程。

**Comment by liuqiiiiiii** [comment]
后来我按照楼主的解决方法查看了自己的 URL Types，发现自己的 URL Schemes 用的还是之前的，错误果然在这里，于是更改过来使问题得到了解决。
 @94cstyles URL Types 的位置在：TARGETS->Info，最后一项就是。
