### ISSUE TITLE
react-native 0.42版本中es6-promise报错

### ISSUE THREAD

**Issue by zhuangchuming** [weflex/react-native-wechat#181]
用bluebird来替换的话，使用微信支付没法调用，打不开微信的界面就直接受到回调，返回支付失败。这个问题目前有什么好的解决方案吗。

**Comment by lizhiren2016** [comment]
通求解决这个问题，希望作者能修改一下

**Comment by magicismight** [comment]
这里完全没有必要使用 promisify ，把原生代码的 callback 参数改成 promise 参数就可以了

**Comment by imtcn** [comment]
修改node_modules es6-promisify dist promise.js
"use strict";

module.exports = (function () { 
    "use strict"; 
    return global.Promise;
})();

临时处理..

**Comment by QHYK** [comment]
我按你说的直接return之后还是会报错

**Comment by yorkie** [comment]
刚发了 1.9.2 版本，可以线上安装尝试一下 :)

**Comment by yorkie** [comment]
应该已经修复了，关掉了～
