### ISSUE TITLE
Calling WeChat.pay get alert "WeChat API invoke returns false"

### ISSUE THREAD

**Issue by yeegr** [weflex/react-native-wechat#185]
`import * as WeChat from 'react-native-wechat'

  async _wechatpay(order) {
    try {
      let result = await WeChat.pay(order.WeChatPay)

      if (result.errCode === 0) {
        Alert.alert(
          'wechat success',
          JSON.stringify(result),
          [
            {text:'okay'}
          ]
        )
      }
    } catch (e) {
      Alert.alert(
        'wechat error',
        JSON.stringify(e),
        [
          {text:'okay'}
        ]
      )
      console.log(e)
    }
  }
`

Any ideas?

**Comment by coneycode** [comment]
how to slove it？

**Comment by yazhengwang** [comment]
@coneycode 
![image](https://user-images.githubusercontent.com/14901532/33361362-bb05611c-d512-11e7-86fc-3bd7fd30142d.png)
