### ISSUE TITLE
微信分享到朋友圈后不能选择停留在微信还是返回app么？

### ISSUE THREAD

**Issue by ycb0318** [weflex/react-native-wechat#186]
分享给朋友是有提供给用户选择是否留在微信，但是分享到朋友圈没有提供这个功能，怎么解决呢？

**Comment by yorkie** [comment]
这个应该是微信自己的产品特性，程序没发控制～

**Comment by ycb0318** [comment]
嗯嗯 我现在也意识到这个问题了，其它app分享到朋友圈，成功后也是直接返回的
