### ISSUE TITLE
android上分享弹不出框

### ISSUE THREAD

**Issue by 12d** [weflex/react-native-wechat#188]
android上分享弹不出框。。调用shareToSession和shareToTimeline都无效，openWeixinApp等其他其他接口正常

**Comment by yorkie** [comment]
是否有按照 https://github.com/weflex/react-native-wechat#linking-android-with-gradle 正常link以及添加对应的Entry呢？

**Comment by 12d** [comment]
解决了。link/entry什么的都没问题。原因是公众平台的服务器配置问题，返回提供调用的callback
