### ISSUE TITLE
react-native和ios原生合成时，undefined is not an object (evaluating 'W.registerApp')

### ISSUE THREAD

**Issue by luojinghui** [weflex/react-native-wechat#190]
项目是rn和原生相互依赖，rn包裹在原生里面，现在做分享，安卓没有问题，ios编译报错：
```
undefined is not an object (evaluating 'W.registerApp')
```
我react-native已经可以分享了，就和合成到ios项目里面，一打包出app后，运行就报这个错误。没思绪，不知道为什么。

![错误截图](http://ol5l1z7pa.bkt.clouddn.com/WechatIMG512.jpeg)

**Comment by luojinghui** [comment]
@yorkie @simman @lijinchao2007 @buhe 求帮助，你们有什么想法吗？

**Comment by luojinghui** [comment]
好吧，以解决。配置出错，改了一下。

**Comment by yorkie** [comment]
:)

**Comment by yokots** [comment]
@luojinghui 改了什么配置，求教一下。

**Comment by luojinghui** [comment]
@yokots 需要仔细的一步一步的按照配置方法走一遍。我之前是rn配置好了，再给原生配置时有个小地方配置错了（貌似是header search paths里面的插件入口），所以找不到wechat.regitsterApp的方法。
