### ISSUE TITLE
怎么分享微信链接

### ISSUE THREAD

**Issue by dandingol03** [weflex/react-native-wechat#193]
我需要用户点击分享的消息后，跳转到特定url进行注册
so,just help me

**Comment by yorkie** [comment]
你思考问题的维度不对，微信SDK是以用户点击源划分的，比如聊天窗口(shareToSession)、朋友圈(shareToTimeline)，如果要分享链接，这两个接口都有`webpageUrl`的属性可以完成你的需求。
