### ISSUE TITLE
IOS登录接口，授权后不会返回

### ISSUE THREAD

**Issue by HyperSimon** [weflex/react-native-wechat#199]
RT

**Comment by yoniji** [comment]
遇到同样的问题，可以调起微信授权界面，点击授权后无反应。

后来发现是配置的问题，需要检查：
1.  公众平台开发配置中 Bundle ID 和开发 Bundle ID 是否正确
2. URL Schema 中 `URL type` 是否和 app id 一致
3. `AppDelegate.m` 中是否有 openURL 方法

我的情况是因为 URL Schema 里 app id 填错了

**Comment by Showyilu** [comment]
我的情况也是
解决方案是使用es7 await 语法
1. yarn add babel-preset-react-native-stage-0 --save-dev
2. 在.babelrc 中加入 "presets": [ "react-native-stage-0" ]

**Comment by HyperSimon** [comment]
@yoniji @Showyilu 谢谢 忘了是怎么解决得了

**Comment by HyperSimon** [comment]
哦 应该是本地的微信id错了
