### ISSUE TITLE
add some example

### ISSUE THREAD

**Issue by iwater** [weflex/react-native-wechat#2]
please add some example code for the api

**Comment by yorkie** [comment]
Ok, I will add this soon later, thanks :-)

**Comment by kinhunt** [comment]
+1

**Comment by kinhunt** [comment]
<img width="370" alt="2015-11-17 9 47 48" src="https://cloud.githubusercontent.com/assets/1231514/11200352/6a69cece-8d10-11e5-9a5e-1cc9c63dc1d6.png">

**Comment by yorkie** [comment]
Oh, this seems to be a bug, may I ask you to put your steps here so that I can know which one you are missing.

> 中文：这个应该是一个Bug，能否请你把你具体的操作步骤发到这里，这样我可以更好地确定哪一个步骤你做错了

**Comment by kinhunt** [comment]
@yorkie 
I followed your Readme instructions by installing the module with npm and linking the libs. Also, I can call the isWXAppInstalled function but it always gives false, even wechat is installed.

**Comment by yorkie** [comment]
@kinhunt could you send me the complete source code especially the `node_modules/react-native-wechat` to `yorkiefixer@gmail.com`? I will take a look :-)

**Comment by yorkie** [comment]
@iwater @kinhunt Added example at https://github.com/weflex/react-native-wechat/tree/master/Example, and v1.1.0 released to fix the error: "WeChat.registerApp is not a function".

Thank you guys :-)

**Comment by kinhunt** [comment]
@yorkie  hooray~ well done
