### ISSUE TITLE
现在Native Module里可以返回Promise

### ISSUE THREAD

**Issue by RockyF** [weflex/react-native-wechat#201]
刚看了源码，感觉您是为了做Promise才把js层写得如此扭捏，其实现在的Native Module可以直接返回Promise了，而不必再写一层Promise。
建议直接返回Promise，使代码更加简洁
[http://reactnative.cn/docs/0.43/native-modules-ios.html#promises](url)

**Comment by yorkie** [comment]
希望可以指出具体不好的地方，先关了
