### ISSUE TITLE
跳转到微信支付后报错 支付验证签名失败

### ISSUE THREAD

**Issue by BumpMonster** [weflex/react-native-wechat#216]
请问我获取到了prepay_id后，也进行了很仔细的签名，调用微信支付API后，调到微信还是提示  支付验证签名失败，这是我的代码   
const currentTimestamp = new Date().getTime();
  let secondUnsigned={
            appid: 'wx***********',
            partnerid: partnerId,  // 商家向财付通申请的商家id
            prepayid: prepay_id,   // 预支付订单
            noncestr: nonceStr,   // 随机串，防重发
            timestamp: currentTimestamp,  // 时间戳，防重发
            package: 'Sign=WXPay',    // 商家根据财付通文档填写的数据和签名
        }
        let secondsigned=sign(secondUnsigned)

        WeChat.pay({
            partnerId: partnerId,  // 商家向财付通申请的商家id
            prepayId: prepay_id,   // 预支付订单
            nonceStr: nonceStr,   // 随机串，防重发
            timeStamp: currentTimestamp,  // 时间戳，防重发
            package: 'Sign=WXPay',    // 商家根据财付通文档填写的数据和签名
            sign: secondsigned
        })
let secondsigned=sign(secondUnsigned)是我写的签名函数，是没问题的，请问是哪里出的问题呢

**Comment by BumpMonster** [comment]
已解决，签名的问题

**Comment by EEvvee** [comment]
请问是签名的什么问题？

**Comment by cnpmge** [comment]
请问是什么问题？签名咋回事啊，我的签名看着没问题啊
