### ISSUE TITLE
Cannot run Example demo

### ISSUE THREAD

**Issue by NancyZY** [weflex/react-native-wechat#24]
Hi,guys! firstly, I installed the project with commmand : npm install react-native-wechat --save
secondly, I entered the directory  ./node_modules/react-native-wechat/Example run with  "npm install " 
then ,  I clicked the "RUN" in Xcode,  
finally, I got the error message -- "Unable to resolve module ./react-native-wechat.js  from /Users/user/Development/Projects/node_modules/react-native-wechat/Example/index.ios.js : Invalid directory /User/user/Development/Projects/node_modules/react-native-wechat/Example/react-native-wechat.js"

How can I run successlly ? Hope your guys answer. Thanks your answer in anvance

**Comment by NancyZY** [comment]
![image](https://cloud.githubusercontent.com/assets/9473445/12197924/71d0ceba-b646-11e5-890f-7488dfa04eb2.png)

**Comment by NancyZY** [comment]
![image](https://cloud.githubusercontent.com/assets/9473445/12197954/c48fd4e8-b646-11e5-8341-5f2eccbe809f.png)

**Comment by yorkie** [comment]
I have resolved this problem by symlink the react-native-wechat/index.js to react-native-wechat/Example/react-native-wechat.js, could you have a try?
