### ISSUE TITLE
[Android]How to use?

### ISSUE THREAD

**Issue by Richard-Cao** [weflex/react-native-wechat#25]
`import WeChat from 'react-native-wechat';`
but `WeChat` undefined
`WeChatPackage` I would import in Android studio

**Comment by Richard-Cao** [comment]
@yorkie

**Comment by yorkie** [comment]
@tdzl2003 could you give some help to this issue :-)

**Comment by Richard-Cao** [comment]
@tdzl2003 help

**Comment by Richard-Cao** [comment]
I know, thx!
