### ISSUE TITLE
can't find variable: nativeShareToTimelineRequest

### ISSUE THREAD

**Issue by anderson916** [weflex/react-native-wechat#27]
![wechat_1454298445](https://cloud.githubusercontent.com/assets/195719/12708349/951e659e-c8d9-11e5-8873-7551def460ab.jpeg)

**Comment by yorkie** [comment]
@anderson916 try with v1.2.5, thank you

**Comment by anderson916** [comment]
different error message but still fail to share.

**Comment by yorkie** [comment]
Could you post the message again?

**Comment by anderson916** [comment]
I did. please check https://github.com/weflex/react-native-wechat/issues/29
