### ISSUE TITLE
nativeShareToTimeline is not a function

### ISSUE THREAD

**Issue by anderson916** [weflex/react-native-wechat#29]
no shareToTimeline function in your RCTWeChat.m. WHY?

**Comment by yorkie** [comment]
I see, because #20 seems to do this for iOS, I will land it soon later.

**Comment by anderson916** [comment]
Thank you. I am waiting for this. When will it be available?

**Comment by yorkie** [comment]
Definitely not sure when, I will try once tonight

**Comment by letmeknowhow** [comment]
any new progress?

**Comment by yorkie** [comment]
Try with v1.3.0

**Comment by letmeknowhow** [comment]
In RCTWeChat.h file, I got a error that RCTBridgeModule.h is not found.
