### ISSUE TITLE
data structure of shareToTimeline and shareToSession

### ISSUE THREAD

**Issue by letmeknowhow** [weflex/react-native-wechat#31]
I always failed to share image use these 2 api, image cant display in share page and would get a message tell me that image send failed.
I do this like below: 
`await WeChat.shareToTimeline({
    type: 'image',
    imageUrl: 'http://pic3.nipic.com/3058118_113506073_2.jpg'
});`
Could you provide some sample code for these two APIs with parameter's data, to let me know how to share a image?

**Comment by xing-zheng** [comment]
please refer the code example here, but my pull request is not accepted by author yet.  #36 
these example need 'react-native-chat' and 'react-native-fs' plugin.
```javascript
import * as WeChat from 'react-native-wechat';
import fs from 'react-native-fs';
var resolveAssetSource = require('resolveAssetSource'); // along with Image component
```

1, code example to share text message:
```javascript
try {
    var result = await  WeChat.shareToTimeline({type: 'text', description: 'I\'m Wechat, :)'});
    console.log('share text message to time line successful', result);
}
catch (e) {
    console.log('share text message to time line failed', e);
}
```
2, code example to share image url:
```javascript
try {
    var result = await WeChat.shareToTimeline({
        type: 'imageUrl',
        title: 'web image',
        description: 'share web image to time line',
        mediaTagName: 'email signature',
        messageAction: undefined,
        messageExt: undefined,
        imageUrl: 'http://shared.ydstatic.com/dict/v5.16/images/logo-entry.png'
    });
    console.log('share image url to time line successful', result);
}
catch (e) {
    console.log('share image url to time line failed', e);
}
```
3, code example to share image file:
```javascript
try {
    var rootPath = fs.DocumentDirectoryPath;
    var savePath = rootPath + '/email-signature-262x100.png'; // like /var/mobile/Containers/Data/Application/B1308E13-35F1-41AB-A20D-3117BE8EE8FE/Documents/email-signature-262x100.png

    await fs.downloadFile('http://www.ncloud.hk/email-signature-262x100.png', savePath);

    var result = await WeChat.shareToTimeline({
        type: 'imageFile',
        title: 'image file download from network',
        description: 'share image file to time line',
        mediaTagName: 'email signature',
        messageAction: undefined,
        messageExt: undefined,
        imageUrl: savePath
    });

    console.log('share image file to time line successful', result);
}
catch (e) {
    console.log('share image file to time line failed', e);
}
```
4, code example to share image resource:
```javascript
try {
    var imageResource = require('./email-signature-262x100.png');
    var result = await WeChat.shareToTimeline({
        type: 'imageResource',
        title: 'resource image',
        description: 'share resource image to time line',
        mediaTagName: 'email signature',
        messageAction: undefined,
        messageExt: undefined,
        imageUrl: resolveAssetSource(imageResource).uri
    });
    console.log('share resource image to time line successful', result);
}
catch (e) {
    console.log('share resource image to time line failed', e);
}
```

**Comment by yorkie** [comment]
Hey @xing-zheng are you interested in that add you as a collaborator of this project?

**Comment by xing-zheng** [comment]
Hey @yorkie I'm so glad to participate in this project, I will continuously contribute code and sample.

I find some work to be done:

- more clarified document and sample code.
- android implement.
- more easy integration progress use rnpm.

**Comment by yorkie** [comment]
Ok, added you as the collaborator with write right now.

**Comment by xing-zheng** [comment]
Thank you! @yorkie

**Comment by letmeknowhow** [comment]
I update to V1.3.1, and got build failed in RCTWeChat.m

Use of undeclared identifier 'RCTResizeModeStretch'

**Comment by xing-zheng** [comment]
the identifier 'RCTResizeModeStretch' is defined in "RCTResizeMode.h" witch is included by "RCTImageUtils.h", they are both reside in the directory "/node_modules/react-native/Libraries/Image".

If you install the react-native-wechat plugin by "npm install react-native-wechat --save" or "react-native link react-native-wechat" command, the "Header Search Path" options of XCode project is defined correctly, Otherwise you should add that directory into the "Header Search Path" manually.

**Comment by yorkie** [comment]
For data structure of using share* methods, see https://github.com/weflex/react-native-wechat/blob/master/index.js#L156-L164, please. reopen this one if any problems still are exist, @letmeknowhow
