### ISSUE TITLE
 'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by gp5251** [weflex/react-native-wechat#32]
I get this error when I upgrade to 1.3.0. how to fix this? 3q.

`/Users/guipeng/Desktop/ldl/dashboard/node_modules/react-native-wechat/ios/RCTWeChat.h:10:9:
 'RCTBridgeModule.h' file not found`

**Comment by Richard-Cao** [comment]
+1 How to solve?

**Comment by vtaseski** [comment]
+100 HOW TO SOLVE?

**Comment by vtaseski** [comment]
I NEED THIS IMMEDIATELY. I TRIED EVERYTHING. HELP!!!!

**Comment by Richard-Cao** [comment]
Upgrade to the latest version. @vtaseski
