### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by Richard-Cao** [weflex/react-native-wechat#33]

**Comment by Richard-Cao** [comment]
#32

**Comment by Richard-Cao** [comment]
@yorkie

**Comment by fakefish** [comment]
+1

**Comment by yorkie** [comment]
What's the screenshot which you get and the search path, this works at my machine~

**Comment by Richard-Cao** [comment]
`/Users/pan/GitHub/reading/node_modules/react-native-wechat/ios/RCTWeChat.h:10:9: 'RCTBridgeModule.h' file not found` build failed 
@yorkie

**Comment by monopieces** [comment]
+1

**Comment by monopieces** [comment]
cd Example && npm install

**Comment by stevenxiale** [comment]
me too, how to deal with this problem

**Comment by stevenxiale** [comment]
$(SRCROOT)/../node_modules/react-native-wechat/ios

**Comment by Richard-Cao** [comment]
@stevenxiale 
change RCTWebChat.xcodeproj → Build Settings → Search Paths → Header Search Paths to
$(SRCROOT)/../../react-native/React and
$(SRCROOT)/../../react-native/Libraries

**Comment by p1204382** [comment]
@Richard-Cao thanks it is work

**Comment by annelorraineuy** [comment]
This failed for me :( 
<img width="825" alt="screen shot 2016-12-02 at 3 38 54 pm" src="https://cloud.githubusercontent.com/assets/5892190/20852858/82b92008-b8a5-11e6-9534-80d57125f550.png">

**Comment by maple-leaf** [comment]
I sovle by upgrading the os from 10.10.x to newest macOS, and the xcode.

**Comment by Extrct** [comment]
If you are using the most recent version of react native (0.40 at time of post) - the proper NativeModule import syntax has changed for your Objective C file:
**#import <React/RCTBridge.h>**
Replace with this. Same syntax will apply for importing RCTUtils.

**Comment by yeegr** [comment]
It would be more helpful if you could specify which "Objective C" files should be edited in this case.

**Comment by Extrct** [comment]
RCTWeChat.h and RCTWeChat.m - or any file referencing a react native file. You'll need to change the import structure of any react file references for 0.40
https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by shakilcse12** [comment]
change the import Line from #import "RCTBridgeModule.h" to #import "React/RCTBridgeModule.h"
solved my problem

**Comment by rajeshpanwar007** [comment]
@annelorraineuy Same error is comming in my project. I have tried and searched a lot but not able to fix. How did you fix it ?

**Comment by waifo** [comment]
I have tried the solutions above, none of them worked
where does this path $(SRCROOT)/../../react-native/React point to...?

**Comment by zhaoquntao** [comment]
change #import <React/RCTBridgeModule.h>
to #import "RCTBridgeModule.h"

**Comment by jeremyfrancis** [comment]
No solution stilll....

**Comment by Alu1911** [comment]
Solution is : 
![screen shot 2018-04-24 at 5 37 55](https://user-images.githubusercontent.com/25991100/39163116-ac716376-4781-11e8-9c63-34faadc80a64.png)

**Comment by zedtux** [comment]
Thank you @BachirKhiati, it solved my issue I had with [a "-cal" target](https://github.com/calabash/calabash-ios/wiki/Tutorial%3A--Creating-a-cal-Target) for [Calabash](https://github.com/calabash/calabash-ios). 👍

**Comment by sturmenta** [comment]
For me it worked like this:

1) xcode -> build settings -> header search paths
2) add `$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK`

Where for you `react-native-fbsdk` is the name of you module and `RCTFBSDK` is the name of the subfolder

**Comment by sultan-arshi** [comment]
change `#import "RCTBridgeModule.h"` to `#import "React/RCTBridgeModule.h"`
