### ISSUE TITLE
Are there plans to develop Android version?

### ISSUE THREAD

**Issue by fukai7722** [weflex/react-native-wechat#4]
RT

**Comment by yorkie** [comment]
@fukai7722 近期没有，因为这个项目是跟 WeFlex 的 iOS 应用深度绑定的，目前还没有计划开发安卓版本，人力也有限，所以暂时没有安卓版本的打算。但不考虑哪天我抽风了，就会写一个出来 :p

**Comment by YComputer** [comment]
我大概一周后要弄一个android 版本了。。。

**Comment by yorkie** [comment]
@YComputer 你的意思是安卓的app，还是 react-native-wechat ? 如果可以，完成后提交一个PR到这里吗？

**Comment by YComputer** [comment]
好。是react-native-wechat 登录分享相关。一起分享。

**Comment by yorkie** [comment]
Ok, 谢谢，期待 :-)

**Comment by buhe** [comment]
赞! 我也挖个坑,如果下周还没有人搞Android ,我就去搞。正好要用

**Comment by yorkie** [comment]
你搞吧。。。 @buhe

**Comment by buhe** [comment]
有个开源项目把android搞好了。 直接用了，这里不引用了，不太合适，毕竟竞品。
:)

**Comment by tdzl2003** [comment]
我这边搞好了一部分，已经在测试了，明天应该就可以放出来。
