### ISSUE TITLE
rename the timeline to moments

### ISSUE THREAD

**Issue by yorkie** [weflex/react-native-wechat#44]
Because the "朋友圈" is named as the word "moments", so we should keep consistent with that :-)

**Comment by xing-zheng** [comment]
```java
    @ReactMethod
    public void shareToTimeline(ReadableMap data, Callback callback) {
        if (api == null) {
            callback.invoke(NOT_REGISTERED);
            return;
        }
        _share(SendMessageToWX.Req.WXSceneTimeline, data, callback);
    }
```
Hi, @yorkie , We can see that, The code from Tencent official SDK use "WXSceneTimeline" to represent "朋友圈".
And I think we should keep our API compatible with previous version instead of breaking it.
