### ISSUE TITLE
0.22.2调用包的时候 app闪退了，是怎么回事，finish（）函数是不是必须调用

### ISSUE THREAD

**Issue by 52myu** [weflex/react-native-wechat#47]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getDeviceInfo(this);//友盟
        // WeChatModule.handleIntent(getIntent());//微信
        // finish();
        
    }
这样是正常的，如果取消注释App就闪退

**Comment by xing-zheng** [comment]
目前此组件尚不支持处理wechat的响应或请求。请不要添加 handleIntent 代码。

不影响分享功能（但无法得知是否分享成功）。

**Comment by yorkie** [comment]
@xing-zheng 你是否知道不支持响应的原因？

**Comment by xing-zheng** [comment]
@yorkie 因为缺少实现代码 :-(

**Comment by yorkie** [comment]
已经开了 #48 来追踪这个问题了。

**Comment by xing-zheng** [comment]
@yorkie OK

**Comment by kitt1987** [comment]
Handling sharing reply has already been supported.

**Comment by yorkie** [comment]
Closed as @kitt1987 mentioned :-)
