### ISSUE TITLE
安卓环境下，文件能分享成功，但是在微信中有些问题

### ISSUE THREAD

**Issue by liuchungui** [weflex/react-native-wechat#51]
有两个问题：
1、在微信中，点击我分享的docx文件进入预览页面，点击“用其他应用打开”时，提示“程序未检测到可以打开此文件的应用”，但我在微信中用其他方式分享的docx文件能检测到应用可以打开。
2、分享文件的缩略图api当中是否可以指定？

**Comment by xing-zheng** [comment]
1、我也发现了你说的问题。还没找到解决方案，我们一起来尝试解决。
2、支持缩略图。

**Comment by liuchungui** [comment]
@xing-zheng 这个问题我已经解决了，提交了一个PR，请看[PR#52](https://github.com/weflex/react-native-wechat/pull/52)
