### ISSUE TITLE
iOS微信登录错误

### ISSUE THREAD

**Issue by pcxiong** [weflex/react-native-wechat#53]
登录部分的文档和Example太简短了，不是很明白。
测试环境下，点击微信登录，可以正常跳转到微信，但是授权回来，就报错：undefined is not an object (evaluating 'v[0]') （错误定位在 https://github.com/weflex/react-native-wechat/blob/master/index.js#L85）

关键代码只有这一行：
`Wechat.sendAuthRequest('snsapi_userinfo', 'SECRET')`

请问是已知问题么？

**Comment by yorkie** [comment]
在你的 appDelegate.m 中有没有如下的代码：

```objc
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                            sourceApplication:sourceApplication annotation:annotation];
}
```

**Comment by pcxiong** [comment]
谢谢。
看来这是必要代码啊，那就不是 “ Note: ” 吧，而且 LinkingIOS 已经 deprecated 了，所以看到这有点困扰，看了 Example 也没有这几行代码 :smile:  。
不好意思打扰了。

**Comment by yorkie** [comment]
嗯 对，是文档不够清楚，这个issue先开着，等文档完善后再关掉好了～

**Comment by ace68723** [comment]
遇到了同样的问题，appDelegate.m中也添加了Linking的代码

**Comment by yorkie** [comment]
报告下版本号

**Comment by ace68723** [comment]
RN:0.24.1
RN-Wechat:1.4.1

**Comment by yorkie** [comment]
> 测试环境下，点击微信登录，可以正常跳转到微信，但是授权回来，就报错：undefined is not an object 
(evaluating 'v[0]') 

@ace68723 是这个错误报告吗？

**Comment by ace68723** [comment]
是的，v[0]的错。v加console.log是undefined

**Comment by ace68723** [comment]
我加断点发现，[WXApi sendReq:req]返回时NO
req参数是用微信官方给的demo   
    req.scope = @"snsapi_userinfo" ;
    req.state = @"123" ;

**Comment by lionrock** [comment]
I‘v meet this error too.

**Comment by ace68723** [comment]
@yorkie  我提交了个pr，抓取auth返回的参数，你review一下，我不太熟练用bluebird，可能写的不是那么efficiency

**Comment by ace68723** [comment]
@lionrock I submitted a pull request, have a try. It works on me :)
https://github.com/weflex/react-native-wechat/pull/60

**Comment by lionrock** [comment]
@ace68723 thx  :- )

**Comment by yorkie** [comment]
Fixed at #60.
