### ISSUE TITLE
android: sendAuthReq Android

### ISSUE THREAD

**Issue by hiwenny** [weflex/react-native-wechat#54]
Can you give an example on how to use the sendAuthReq in Android please? I've been following the example in the iOS version but it only returns undefined after app registration.

**Comment by ace68723** [comment]
@hiwenny I rebuild sendAuthRequest method. It's works on me (iOS), but I didn't try on android.
https://github.com/weflex/react-native-wechat/pull/60

**Comment by yorkie** [comment]
This seems to be a signature problem, and it's duplicated with #84, closing this one.
