### ISSUE TITLE
android环境下rnpm链接的问题

### ISSUE THREAD

**Issue by liuchungui** [weflex/react-native-wechat#55]
当我另外clone工程的时候，使用rnpm install一键式安装所有package.json中的第三方组件时，Wechat导出了两个组件，一个是RCTWeChat，另外一个是react-native-wechat，我删除了其中一个和相关依赖就行了，能否修改下，让安装更方便

**Comment by yorkie** [comment]
我不是太明白 rnpm 的工作方式，能否把你的改动提交上来？@liuchungui

**Comment by liuchungui** [comment]
@yorkie 等我改了，提交给你

**Comment by liuchungui** [comment]
这个没有问题
