### ISSUE TITLE
unable LinkingIOS: undeclared identifier 'RCTLinkingManager'

### ISSUE THREAD

**Issue by lionrock** [weflex/react-native-wechat#56]
/AppDelegate.m: Use of undeclared identifier 'RCTLinkingManager'

**Comment by yorkie** [comment]
What's your React-Native version?

**Comment by lionrock** [comment]
Sorry, I forgot to import it

**Comment by yorkie** [comment]
Never mind.

**Comment by chandniKkpl** [comment]
I import it but it is showing 'RCTLinkingManager.h' file not found

**Comment by piclez** [comment]
I was getting RCTLinkingManager.h' file not found as well, but this solved for me:

`#import <React/RCTLinkingManager.h>`

**Comment by Mussabaheen** [comment]
Kindly make sure that you place the

    `#import <React/RCTLinkingManager.h>`

in the Appdelegate.m file above the

   ` #ifdef FB_SONARKIT_ENABLED`

it worked for us.

**Comment by waleed2812** [comment]
already have it does not work for me.

EDIT: It works ONLY if you import it above #ifdef FB_SONARKIT_ENABLED
