### ISSUE TITLE
请问，现在支持微信支付了吗

### ISSUE THREAD

**Issue by zhenlovezhen2012** [weflex/react-native-wechat#57]
请问，现在支持微信支付了吗

**Comment by yorkie** [comment]
并不支持，估计短期内也没有支持的计划，建议可以用 https://github.com/weflex/react-native-pingpp

**Comment by zccan** [comment]
@yorkie 你这个包https://github.com/weflex/react-native-pingpp不支持android啊，还有一个包https://github.com/lvbingru/react-native-pingxx和你的有冲突，不能同时使用。吐血

**Comment by yorkie** [comment]
你可以把 react-native-wechat 的动态库移除掉，应该就不冲突了

**Comment by HADB** [comment]
希望可以早点支持支付啊！

**Comment by yorkie** [comment]
暂时关闭这个，重复的问题 #39
