### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by cham1985** [weflex/react-native-wechat#58]
大神,登录API在哪啊

**Comment by cham1985** [comment]
找到了是 sendAuthRequest([scope[, state]]) 方法,但是 参数怎么传啊,求例子

**Comment by yorkie** [comment]
https://github.com/weflex/react-native-wechat#sendauthrequestscope-state scope你要看微信的[文档](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842&token=&lang=zh_CN)，合法的字段是：

- `snsapi_base`
- `snsapi_userinfo`

**Comment by cham1985** [comment]
此方法是不是 只返回 
第二步：通过code获取access_token

**Comment by cham1985** [comment]
此方法是不是只返回 
{
    "code": "",
    "appid": "",
    "lang": "",
    "country": "",
}
这种数据结构,第二步：通过code获取access_token  是不是还得我自己实现方法啊 ?

**Comment by cham1985** [comment]
var result = await WeChat.sendAuthRequest('snsapi_userinfo', "123");
ToastAndroid.show('登录成功==' + result, ToastAndroid.LONG);

为何 result 显示 undefined ?

**Comment by yorkie** [comment]
```objc
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                            sourceApplication:sourceApplication annotation:annotation];
```
Delegate.m 中是否有这段代码？

**Comment by cham1985** [comment]
有的

**Comment by cham1985** [comment]
而且我测试的是 安卓

**Comment by ace68723** [comment]
@cham1985 我也遇到了这个问题抓不到result，我修改了一下，可以在ios用。没试过安卓，你可以试试。https://github.com/weflex/react-native-wechat/pull/60

**Comment by cham1985** [comment]
@ace68723  你IOS 怎么修改的?

**Comment by ace68723** [comment]
@cham1985 pull request 里面有呀，你看看，安卓的应该也能用
