### ISSUE TITLE
分享到朋友群,必须要注册微信开发者账号? 获取API KEY吗?

### ISSUE THREAD

**Issue by sulliwane** [weflex/react-native-wechat#6]
你好,

请问一下, 我只是想用"分享到朋友群"功能, 没有一个微信APP KEY就做不了吗?

谢谢

**Comment by yorkie** [comment]
嗯 应该是的，因为微信分享在朋友圈都要会有一个名字显示在下面，所以应该是需要去微信那边申请应用的。

**Comment by sulliwane** [comment]
那我不明白为什么安卓上面有一些欧洲的app他们提供这个"分享到微信群"的功能, 但是他们肯定没有注册微信账号...
谢谢你的回复.

**Comment by yorkie** [comment]
欧洲的 App? 比如什么？安卓平台我不是太了解，估计安卓有一些 hacking 吧 :-(
