### ISSUE TITLE
Android: Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by cham1985** [weflex/react-native-wechat#63]
Module AppRegistry is not a registered callable module.
Unhandled JS Exception: Cannot read property 'registerApp' of undefined
Unhandled JS Exception: Module AppRegistry is not a registered callable module.

**Comment by yorkie** [comment]
请报告一下你使用的是 Android 还是 iOS，谢谢了～

**Comment by yanghuxiao** [comment]
0.25.1适配问题，参考官方升级文档修改下

**Comment by cham1985** [comment]
是 IOS 上的, 就是 import * as WeChat from 'react-native-wechat';  这句 没得到 WeChat 对象

**Comment by cham1985** [comment]
@yanghuxiao  我的 RN 是 0.24.1

**Comment by yorkie** [comment]
用 https://github.com/weflex/react-native-wechat/blob/master/Example/index.ios.js#L15 可以 work 吗？@cham1985

**Comment by devjiangzhou** [comment]
@yorkie  您好，我在0.27.2下 也遇到这个问题了

**Comment by jiangqqlmj** [comment]
i solved this bug！

i have create a new function in WeChatModule.java  eg:

 public boolean canOverrideExistingModule(){
        return true;
    }

**Comment by yorkie** [comment]
Hi @jiangqqlmj may I ask you to submit your patch via Pull Request, thanks :-)

**Comment by jiangqqlmj** [comment]
OK~so i will submit PR~

**Comment by aqnaruto** [comment]
@yorkie  我真想不通为什么安卓部署要加那么多东西，然后还跑不了，如果你要加那么多东西 写个脚本解压不好么。

**Comment by yorkie** [comment]
@aqnaruto talk is cheap, pr is welcome :)

**Comment by movetosun** [comment]
明明面向的中国的开发者,搞什么英语,整的好像全世界都在用一样
