### ISSUE TITLE
Android分享闪退

### ISSUE THREAD

**Issue by dongrenguang** [weflex/react-native-wechat#64]
如题。按照[android分享不可用](https://github.com/weflex/react-native-wechat/issues/59) 里说的解决方法（重装微信与应用）还是不行。求解

**Comment by dongrenguang** [comment]
闪退应该是apk的签名问题，重新生成了签名后不闪退了。但是，分享新闻（type = 'news'）还是有问题，shareToTimeline() / shareToSession()的返回值为false。其中设置了type（值为'news'）、thumbImage、title、description、webpageUrl这几个属性。望解决。

PS：最终转向了[react-native-wechat-android](https://github.com/beefe/react-native-wechat-android)模块，并分享成功。虽然这个模块只支持Android。。。

**Comment by kiliwalk** [comment]
我也碰到这个问题了, 闪退. 不过后面通过获取debug模式下app的签名, 重新在开放平台里修改了下, 然后重启自己的APP, 就可以了分享了. 不重启自己的APP不行

**Comment by CDog34** [comment]
我们遇到了同样的问题，调了shareToSession之后跳去微信转了一会儿菊花，之后直接退回到应用。Logcat得到如下日志：


09-13 16:06:31.408 22513 22513 I Timeline: Timeline: Activity_launch_request id:com.tencent.mm time:20373987
09-13 16:06:31.409  1726  1738 I ActivityManager: START u0 {flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras)} from uid 10313 on display 0
09-13 16:06:31.433 22513 22553 I ReactNativeJS: '[Debug.jq:res]:', true
09-13 16:06:31.596  1726  1736 I art     : Background partial concurrent mark sweep GC freed 230668(12MB) AllocSpace objects, 22(968KB) LOS objects, 22% free, 53MB/69MB, paused 1.482ms total 173.822ms
09-13 16:06:31.633  1726  1942 I ActivityManager: Displayed com.tencent.mm/.plugin.base.stub.WXEntryActivity: +195ms
09-13 16:06:31.634  6832  6832 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@bd79a8b time:20374213
09-13 16:06:31.895  1726  1942 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{874324e u0 com.tencent.mm/.plugin.base.stub.WXEntryActivity t51} time:20374474
09-13 16:06:32.148   759   759 I MSM-irqbalance: Decided to move IRQ132 from CPU0 to CPU1
09-13 16:06:32.228  1726  3763 W ActivityManager: Finishing task with all activities already finished
09-13 16:06:32.228  1726  3763 W ActivityManager: Duplicate finish request for ActivityRecord{874324e u0 com.tencent.mm/.plugin.base.stub.WXEntryActivity t51 f}
09-13 16:06:32.271 22513 22513 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@38f9ba5 time:20374850
09-13 16:06:32.300 22513 22553 I ReactNativeJS: [CodePush] Reporting binary update (1.0.0)

**Comment by yorkie** [comment]
@CDog34 APK 重新签名过么？
