### ISSUE TITLE
支持rnpm安装吗？

### ISSUE THREAD

**Issue by zh-wowtv** [weflex/react-native-wechat#65]
请问本项目支持rnpm安装吗？谢谢

**Comment by dongrenguang** [comment]
可以的，安装了rnpm模块后(gloabal)，执行
`rnpm link react-native-wechat`
就可以了

**Comment by zh-wowtv** [comment]
ok, 谢谢。要允许login的话，必须在wechat注册交300块才行吧？不是大陆的公司，估计不行吧？

**Comment by dongrenguang** [comment]
@zh-wowtv 300块，竟有这事？太贵了吧

**Comment by zh-wowtv** [comment]
是啊，一年300塊。而且，境外公司無法註冊。

**Comment by yorkie** [comment]
@dongrenguang 如果可以的话，可以麻烦你提一个pr把rnpm的安装教程加到readme里面么？谢谢了
