### ISSUE TITLE
Android上登录授权后闪退

### ISSUE THREAD

**Issue by songyouwei** [weflex/react-native-wechat#66]
使用版本1.4.0
sendAuthRequest可以resolve，调起微信并点确认后，返回时App crash。是Android上SendAuth.Resp的回调监听方面的问题？

PS：iOS上登录和分享都没有问题，Android上分享没问题

**Comment by yorkie** [comment]
是否跟 https://github.com/weflex/react-native-wechat/issues/64 问题类似？

**Comment by songyouwei** [comment]
跟 #64 应该不是同类问题，Android上分享没问题，调起登录授权页没问题，但点确认出现闪退。

**Comment by songyouwei** [comment]
找到原因了，是我这边写的WXEntryActivity的问题。
