### ISSUE TITLE
sendAuthRequest

### ISSUE THREAD

**Issue by rengasahusoft** [weflex/react-native-wechat#67]
What are param values that has to passed inside the sendAuthrequest Function , can you provoide any example for WeChat Authentication

**Comment by yorkie** [comment]
See https://github.com/weflex/react-native-wechat#sendauthrequestscope-state for example, if you want to get the available values for `scope` and `state`, those are:

- `scope`: `snsapi_base` and `snsapi_userinfo`
- `state`: any valid string with a limited length

For full documentation, see: http://admin.wechat.com/wiki/index.php?title=User_Profile_via_Web for English version.
