### ISSUE TITLE
请问为什么分享给好友的图片不显示，好严重！

### ISSUE THREAD

**Issue by Kennytian** [weflex/react-native-wechat#68]
### 分享给好友的图片默认不显示，非要点击灰色默认图跳转到另一个页面，下载后才显示？ 请请教大家一下是什么原因？

补充说明：Android 手机分享给 iOS 手机，分享代码如下：

<pre><code>await WeChat.shareToSession({
	type: 'imageUrl',
	title: 'web image',
	description: 'share web image to time line',
	mediaTagName: 'email signature',
	messageAction: undefined,
	messageExt: undefined,
	//imageUrl: 'http://www.ncloud.hk/email-signature-262x100.png'
	imageUrl: 'http://img.tougudashi.com/share/1463218403.3611000.png'
});</pre></code>

![分享的图片不显示](http://ww4.sinaimg.cn/mw690/006mYm1Pgw1f4h1g6dp6rj30ku1120vh.jpg)

@yorkie  @dongrenguang @cham1985 @yanghuxiao @shiguoqing @Leon1108 @ace68723 @hiwenny @xing-zheng @kitt1987 @letmeknowhow  请帮忙看看，不好意思，打扰到这么多人，谢谢！

**Comment by yorkie** [comment]
你是说在微信朋友圈里么？

**Comment by Kennytian** [comment]
是在的 App 里分享图片给微信好友 @yorkie ，就出现我上述的问题

**Comment by kitt1987** [comment]
You have to set **thumbImage**  as preview here. @Kennytian

**Comment by Kennytian** [comment]
@kitt1987 set  property **thumbImage** can not work, :(

**Comment by yorkie** [comment]
@Kennytian 能否给出你加入 `thumbImage` 的代码，[这里的代码](https://github.com/weflex/react-native-wechat/blob/master/android/src/main/java/com/theweflex/react/WeChatModule.java#L166)是显示 work 的，谢谢。

**Comment by Kennytian** [comment]
@yorkie @kitt1987  谢谢两位，可以显示了，是我的thumbImage太大了，换了一个小的就可以。

但我还是不确定thumbImage的size x size 是多少？  length 是多少kb， 知道是哪儿可以查出？

**Comment by kitt1987** [comment]
@Kennytian  [Android SDK Documentation](https://open.weixin.qq.com/zh_CN/htmledition/res/dev/document/sdk/android/index.html)
