### ISSUE TITLE
WeChatSDK1.7 add module

### ISSUE THREAD

**Issue by JustFavor** [weflex/react-native-wechat#69]
最近微信开放平台更新的sdk1.7版本添加进微信模块里去，在项目里sdk的文件报错，感觉挺莫名其妙的

**Comment by yorkie** [comment]
是的，因为 ios 最近貌似默认使用 http2，所以需要升级老的 sdk，不过我在 https://github.com/weflex/react-native-wechat/pull/62 中失败了，稍后我会再试试。

**Comment by JustFavor** [comment]
RCTWeChat.m的240行imageObject.imageUrl = imageURL这行代码报错了

**Comment by yorkie** [comment]
> RCTWeChat.m的240行imageObject.imageUrl = imageURL这行代码报错了

@JustFavor 是因为引入了1.7的包？

**Comment by JustFavor** [comment]
是的，我把1.7的包替换了你之前旧的sdk

**Comment by JustFavor** [comment]
@yorkie  请问1.7的sdk有加上吗？ 我在你的组件里用了其他的方法把1.7的sdk加上了。

**Comment by yorkie** [comment]
暂时还没有呢，我这边编译一直有问题，我得再看看。

**Comment by JustFavor** [comment]
因为我不需要分享 我把你的分享图片里面的一个参数注释了，我这边已经可以正常用了

**Comment by JustFavor** [comment]
因为我不需要分享 我把你的分享图片里面的一个参数注释了，我这边已经可以正常用了
