### ISSUE TITLE
How to get auth data

### ISSUE THREAD

**Issue by kinhunt** [weflex/react-native-wechat#7]
I am now able to use sendAuthRequest, it opens wechat as expected. How to receive the response data?

Is the onResp bridge missing?

**Comment by yorkie** [comment]
Hey @kinhunt Do you get the response in callback?

**Comment by yorkie** [comment]
BTW, you could join our [gitter room](https://gitter.im/weflex/react-native-wechat?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to catch me in this type of issue.

**Comment by yannxiao** [comment]
This component can get the response: [react-native-wechat-ios](https://github.com/beefe/react-native-wechat-ios)

**Comment by yorkie** [comment]
Closed because this has been added at https://github.com/weflex/react-native-wechat/blob/master/index.js#L142-L149. Thanks
