### ISSUE TITLE
ios微信端分享成功之后返回失败

### ISSUE THREAD

**Issue by zhouzefei** [weflex/react-native-wechat#71]
当微信端分享成功之后，点击返回我的app失败，仍然停留在微信端。

**Comment by yorkie** [comment]
@zhouzefei 关掉了是因为解决了吗？

**Comment by zhouzefei** [comment]
是的，之前不太了解。需要在xcode中配置微信跳转的url types！

**Comment by huangxiaohao** [comment]
您好，我也遇到这个问题，点击返回我的app失败，仍然停留在微信端。
请问如何在xcode中配置微信跳转的url types？ 谢谢！
