### ISSUE TITLE
Image Share via shareToTimeline api Fails 

### ISSUE THREAD

**Issue by rengasahusoft** [weflex/react-native-wechat#75]
When we share an image to wechat moment image is not sending(or shared) and if we send only text it is getting sent (or shared) successfully

resolve this issue

**Comment by yorkie** [comment]
@rengasahusoft could you give the specific version and an complete example code to show this problem, thanks :-)

**Comment by rengasahusoft** [comment]
@yorkie  vesion 1.4.6

before calling this i am calling the api to register this app

let result = await WeChat.shareToTimeline({
            type: 'imageUrl',
            title: 'web image',
            description: 'share web image to time line',
            mediaTagName: 'email signature',
            messageAction: undefined,
            messageExt: undefined,
            imageUrl: 'http://res.cloudinary.com/hbp3fdj8n/image/upload/v1466676197/dtjyyhdzserksbd6c7lv.jpg'
          });
          console.log('share image url to time line successful:', result);
        } catch (e) {
          console.log('share image url to time line failed with:', e);
        }

**Comment by rengasahusoft** [comment]
type : imageUrl   doesn't work 
use type : imageFile object cofiguration  -  it works fine

**Comment by yorkie** [comment]
Could you try with the new release v1.5.1 for imageUrl, because I used the react-native's new `NSURIRequest` for that, thank you :-)
