### ISSUE TITLE
分享时，图片url不能解析

### ISSUE THREAD

**Issue by chfight** [weflex/react-native-wechat#77]
你好，我用react native的 RCTImageStoreManager中的imageStoreManager方法返回了一个图片的URL（比如rct-image-store://0），但我想用这个url以emoticon的方式分享到微信时，并不能打开微信。请问这个问题能解决吗？

**Comment by yorkie** [comment]
因为这个URL是本地的文件或者是自定义的协议，所以你需要把这个图片的URL转化成内容再调用分享的接口进行分享。

**Comment by chfight** [comment]
嗯，谢谢
