### ISSUE TITLE
Link RCTWeChat library from your node_modules/react-native-wechat/ios folder like react-native's [Linking Libraries iOS Guidance], Note: Don't forget to add it to "Build Phases" of your target project.

### ISSUE THREAD

**Issue by iosfucker** [weflex/react-native-wechat#78]
Thanks for the examples on Xcode,I am a  real newer for react native,hoping to  run this code on my Xcode,but as i read the ReadMe document,i have been blocked into the first step,How to  Link RCTWeChat library from your node_modules/react-native-wechat/ios folder? I searched the https://facebook.github.io/react-native/
and found no answer.I guess is it to copy a node_modules file to the Object file? Hope for response!

**Comment by yorkie** [comment]
See https://developer.apple.com/library/ios/recipes/xcode_help-project_editor/Articles/AddingaLibrarytoaTarget.html @iosfucker
