### ISSUE TITLE
请问 shareToSession 或 timeline 的时候 description 如何设置文字换行？

### ISSUE THREAD

**Issue by someok** [weflex/react-native-wechat#80]
rt

**Comment by someok** [comment]
已解决， \n 就可以，之前写了 \\n 了

**Comment by zhuozp** [comment]
@someok 请问下，你加了这个之后，android手机分享的时候，文本换行生效吗？我这边也是用了\n,但是在ios可以，在android就不生效了。

**Comment by someok** [comment]
@zhuozp 汗，我忘了，好像只在 ios 下测试了，没在 Android 下测。。。
