### ISSUE TITLE
React Native 0.29 之后分享到微信的时候提示 RCTImageLoader loadImageWithTag 过期

### ISSUE THREAD

**Issue by someok** [weflex/react-native-wechat#81]
环境：
RN： 0.29
react-native-wechat：1.4.7

提示信息

> [RCTImageLoader loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock:] is deprecated. Instead use [RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:]

**Comment by yorkie** [comment]
这个是警告，应该不影响正常使用的？

**Comment by someok** [comment]
@yorkie 不影响，只是每次都出现个黄条挺烦的

**Comment by yorkie** [comment]
好的，晚上我提个patch更新下`RCTImageLoader`，多谢反馈～

**Comment by yorkie** [comment]
已经在 v1.5.0 中使用`loadImageWithURLRequest`代替 @someok

**Comment by someok** [comment]
多谢，马上升级
