### ISSUE TITLE
iOS工程可以把目标版本降到8.0吗？

### ISSUE THREAD

**Issue by chenjsa** [weflex/react-native-wechat#85]
现在代码中默认是iOS 9.0，但是目前这个阶段还需要兼顾8.0的系统，每次都要手动改版本。如果是用CI工具打包，非常麻烦，而且容易出错。

**Comment by chenjsa** [comment]
<img width="388" alt="2016-07-20 10 10 32" src="https://cloud.githubusercontent.com/assets/2267537/16989457/e4186096-4ec6-11e6-81a7-64bb3d08c641.png">

**Comment by yorkie** [comment]
@chenjsa 你可以提一个 pr 来更新这个么？多谢

**Comment by chenjsa** [comment]
[https://github.com/weflex/react-native-wechat/pull/86](url)

**Comment by yorkie** [comment]
Fixed at #86 and published as v1.5.2, thank you @chenjsa
