### ISSUE TITLE
Breaks on 0.30

### ISSUE THREAD

**Issue by yeegr** [weflex/react-native-wechat#87]
The following build commands failed:
	CompileC /Users/yeegr/Desktop/t2/ios/build/Build/Intermediates/RCTWeChat.build/Debug-iphonesimulator/RCTWeChat.build/Objects-normal/x86_64/RCTWeChat.o RCTWeChat.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/yeegr/Desktop/t2/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (runIOS.js:102:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by yorkie** [comment]
This breaking error is not from react-native-wechat, it's your promise library, and I don't think it's a build error, and it looks like a runtime stack trace more.

@yeegr may I ask you to show more your code to reproduce this bug?

**Comment by yorkie** [comment]
Closed because of inactivity, @yeegr ping me here if you have any updates :-)
