### ISSUE TITLE
#import "RCTBridgeModule.h"  not found RCTBridgeModule.h

### ISSUE THREAD

**Issue by wushuirenjia** [weflex/react-native-wechat#88]
how to fit it?

**Comment by yorkie** [comment]
Which versions(react-native/react-native-wechat) do you use? and could you please print the complete stack trace of this error, thank you :-)

**Comment by Kennytian** [comment]
#import "RCTBridgeModule.h" file not found +1

**Comment by Kennytian** [comment]
Header Search Paths
$(SRCROOT)/../../react-native/React                           recursive
$(SRCROOT)/../../react-native/Libraries/Image          recursive or non-recursive
I fixed this issue, it's working now 👍

**Comment by wushuirenjia** [comment]
@Kennytian perfect, thank you!
