### ISSUE TITLE
希望能接手本模块的维护

### ISSUE THREAD

**Issue by tdzl2003** [weflex/react-native-wechat#9]
您好，我是[React Native中文网](http://react-native.cn/)的站长，我们目前正在收集&整理&维护React Native的相关模块，我们希望能够在npm上接手本模块的持续维护更新，不知是否可以转让对应的npm包名？

谢谢。

**Comment by yorkie** [comment]
转让包名基本是不可以的，因为这个模块我们团队会一直维护，不过如果你们有兴趣，可以把你们添加到 Github/NPM 的协作者列表一起维护。

**Comment by tdzl2003** [comment]
好啊，希望可以加入。我的npm用户名和github用户名都是tdzl2003

**Comment by yorkie** [comment]
添加你成Github的协作者了，NPM的发布暂时还是由我们团队来做，然后一开始我还是希望以PR的工作流来进行，谢谢 @tdzl2003

**Comment by tdzl2003** [comment]
OK :)
