### ISSUE TITLE
RCTWeChat.h:10:9: 'RCTBridgeModule.h' file not found build failed 关闭的Issues都看过无效

### ISSUE THREAD

**Issue by tungh** [weflex/react-native-wechat#93]
目前最新的wechat用cnpm安装后
change RCTWebChat.xcodeproj → Build Settings → Search Paths → Header Search Paths to
$(SRCROOT)/../../react-native/React and
$(SRCROOT)/../../react-native/Libraries 这些都有自带
然后依然出错

**Comment by yorkie** [comment]
```
$ cat node_modules/react-native-wechat/package.json | grep version
```
结果是？

**Comment by tungh** [comment]
"version": "1.5.3",

**Comment by yorkie** [comment]
@tungh 检查一下是否存在"node_modules/react-native/React/Base/RCTBridgeModule.h"？

**Comment by tungh** [comment]
存在

**Comment by yorkie** [comment]
@tungh 你可以加到QQ群里问问看其他在使用的童鞋，可能有遇到跟你类似的情况的，我这里暂时没有发现不 work 的原因。

**Comment by Lotuslwb** [comment]
sudo  rnpm uninstall react-native-wechat  && sudo rnpm install react-native-wechat  

然后就可以了~不明觉厉~~
